//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnetproject.bal2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="bal2.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/balancheck", ReplyAction="http://tempuri.org/IService/balancheckResponse")]
        string balancheck(string accno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/balancheck", ReplyAction="http://tempuri.org/IService/balancheckResponse")]
        System.Threading.Tasks.Task<string> balancheckAsync(string accno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/amountreduce", ReplyAction="http://tempuri.org/IService/amountreduceResponse")]
        int amountreduce(string accno, int uid, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/amountreduce", ReplyAction="http://tempuri.org/IService/amountreduceResponse")]
        System.Threading.Tasks.Task<int> amountreduceAsync(string accno, int uid, int amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : dotnetproject.bal2.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<dotnetproject.bal2.IService>, dotnetproject.bal2.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string balancheck(string accno) {
            return base.Channel.balancheck(accno);
        }
        
        public System.Threading.Tasks.Task<string> balancheckAsync(string accno) {
            return base.Channel.balancheckAsync(accno);
        }
        
        public int amountreduce(string accno, int uid, int amount) {
            return base.Channel.amountreduce(accno, uid, amount);
        }
        
        public System.Threading.Tasks.Task<int> amountreduceAsync(string accno, int uid, int amount) {
            return base.Channel.amountreduceAsync(accno, uid, amount);
        }
    }
}
